version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - chmod +x gradlew
      - ./gradlew --version
      - chmod +x scripts/*.sh
  build:
    commands:
      - rm -rf build/test-results/test build/reports/tests/test
      - JWT_PRIVATE_KEY_PATH=src/test/resources/jwt/private.pem JWT_PUBLIC_KEY_PATH=src/test/resources/jwt/public.pem JWT_CURRENT_KID=test-key ./gradlew cleanTest test --rerun-tasks --stacktrace --info
  post_build:
    commands:
      - ./gradlew bootJar -x test

artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
    - scripts/**/*
