CREATE TABLE metric_descriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_id BIGINT NOT NULL,
  description VARCHAR(4000) NOT NULL,
  interpretation VARCHAR(4000),
  action_hint VARCHAR(4000),
  locale VARCHAR(10) NOT NULL DEFAULT 'ko',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  created_by BIGINT,
  updated_by BIGINT,
  CONSTRAINT uk_md_metric_locale UNIQUE (metric_id, locale),
  CONSTRAINT fk_md_metric FOREIGN KEY (metric_id) REFERENCES metrics(id) ON DELETE CASCADE
);

CREATE TABLE company_key_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  quarter_id BIGINT NOT NULL,
  report_version_id BIGINT,
  internal_health_score DECIMAL(6,2),
  external_health_score DECIMAL(6,2),
  composite_score DECIMAL(6,2),
  risk_level VARCHAR(10) NOT NULL DEFAULT 'SAFE',
  calculation_logic_ver INT NOT NULL DEFAULT 1,
  calculated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  created_by BIGINT,
  updated_by BIGINT,
  CONSTRAINT uk_ckm_company_quarter UNIQUE (company_id, quarter_id),
  CONSTRAINT fk_ckm_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ckm_quarter FOREIGN KEY (quarter_id) REFERENCES quarters(id) ON DELETE CASCADE,
  CONSTRAINT fk_ckm_version FOREIGN KEY (report_version_id) REFERENCES company_report_versions(id) ON DELETE SET NULL,
  CONSTRAINT chk_ckm_risk_level CHECK (risk_level IN ('SAFE','WARN','RISK'))
);

CREATE INDEX idx_ckm_quarter_risk_lookup ON company_key_metrics(quarter_id, risk_level, composite_score DESC);
CREATE INDEX idx_ckm_company_latest ON company_key_metrics(company_id, deleted_at, calculated_at DESC);
CREATE INDEX idx_ckm_version_trace ON company_key_metrics(report_version_id);

CREATE TABLE key_metric_descriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_code VARCHAR(30) NOT NULL,
  metric_name VARCHAR(100) NOT NULL,
  unit VARCHAR(20),
  description VARCHAR(4000) NOT NULL,
  interpretation VARCHAR(4000),
  action_hint VARCHAR(4000),
  weight DECIMAL(3,2),
  threshold_safe DECIMAL(6,2),
  threshold_warn DECIMAL(6,2),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  created_by BIGINT,
  updated_by BIGINT,
  CONSTRAINT uk_kmd_code UNIQUE (metric_code)
);

CREATE INDEX idx_kmd_active ON key_metric_descriptions(is_active, deleted_at);
