CREATE TABLE `metric_averages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `quarter_id` BIGINT NOT NULL COMMENT '분기 ID',
  `metric_id` BIGINT NOT NULL COMMENT '지표 ID (metrics.id)',
  `avg_value` DECIMAL(20,4) NULL COMMENT '전체 기업 평균',
  `median_value` DECIMAL(20,4) NULL COMMENT '중간값',
  `min_value` DECIMAL(20,4) NULL,
  `max_value` DECIMAL(20,4) NULL,
  `stddev_value` DECIMAL(20,4) NULL COMMENT '표준편차',
  `company_count` INT NOT NULL DEFAULT 0 COMMENT '평균 산출에 사용된 기업 수',
  `calculated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '집계 시각',
  `data_source_version` INT NOT NULL DEFAULT 1 COMMENT '집계 로직 버전',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `created_by` BIGINT NULL,
  `updated_by` BIGINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_quarter_metric` (`quarter_id`, `metric_id`),
  INDEX `idx_ma_quarter` (`quarter_id`),
  INDEX `idx_ma_metric` (`metric_id`),
  CONSTRAINT `fk_ma_quarter` FOREIGN KEY (`quarter_id`) REFERENCES `quarters`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_ma_metric` FOREIGN KEY (`metric_id`) REFERENCES `metrics`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='분기별 지표 전체 기업 평균 집계';
