CREATE TABLE `risk_score_summaries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL,
  `quarter_id` BIGINT NOT NULL,
  `report_version_id` BIGINT NOT NULL,
  `risk_score` DECIMAL(6,2) NULL COMMENT '위험 점수 (0~100)',
  `risk_level` ENUM('SAFE', 'CAUTION', 'DANGER', 'UNDEFINED') NOT NULL COMMENT '위험도',
  `risk_metrics_count` INT NOT NULL DEFAULT 0 COMMENT '집계된 위험 지표 수',
  `risk_metrics_avg` DECIMAL(6,2) NULL COMMENT '위험 지표 평균 (원본 단위)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `created_by` BIGINT NULL,
  `updated_by` BIGINT NULL,
  `calculated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_refreshed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_company_quarter_version` (`company_id`, `quarter_id`, `report_version_id`),
  INDEX `idx_rss_quarter` (`quarter_id`, `risk_level`),
  INDEX `idx_rss_company_level` (`company_id`, `risk_level`),
  CONSTRAINT `fk_rss_company` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_rss_quarter` FOREIGN KEY (`quarter_id`) REFERENCES `quarters`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_rss_report_version` FOREIGN KEY (`report_version_id`) REFERENCES `company_report_versions`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='기업-분기별 위험도 요약';
